package com.example.talktalk;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import android.app.ProgressDialog;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Toast;

import com.example.talktalk.Models.Users;
import com.example.talktalk.databinding.ActivitySignUpBinding;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.database.FirebaseDatabase;

public class SignUpActivity extends AppCompatActivity {

    // 1. ViewBinding
    ActivitySignUpBinding binding;

    //2.
    private FirebaseAuth mAuth;
    FirebaseDatabase database;

    //3. creating the progress indicator
    ProgressDialog progressDialog;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // 1. With the help of Binding, we can access all
        // the values, textfields,... inside "activity_sign_up.xml"
        binding = ActivitySignUpBinding.inflate(getLayoutInflater());
        setContentView (binding.getRoot());

        // 2. Initialize Firebase Auth + dataBase
        mAuth = FirebaseAuth.getInstance();
        database = FirebaseDatabase.getInstance();

        //3. Creating a Progress dialog and passing the signUp Activity as param
        progressDialog = new ProgressDialog(SignUpActivity.this);
        progressDialog.setTitle("Creating Account");
        progressDialog.setMessage("Creating Talk-Talk Account in progress");


        //4.Sign Up button
        binding.btnSignUp.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                //Input Control
                if (!binding.txtUsername.getText().toString().isEmpty() && !binding.txtEmail.getText().toString().isEmpty() && !binding.txtPassword.getText().toString().isEmpty()) //!empty = NOT empty
                {
                    //Creating an account when all credentials are filled
                    progressDialog.show();
                    mAuth.createUserWithEmailAndPassword(binding.txtEmail.getText().toString(),binding.txtPassword.getText().toString()).addOnCompleteListener(new OnCompleteListener<AuthResult>() {
                        @Override
                        public void onComplete(@NonNull Task<AuthResult> task) {
                            progressDialog.dismiss();
                            if (task.isSuccessful())
                            {
                                //Making a user object (from users Model)
                                Users user = new Users(binding.txtUsername.getText().toString(),binding.txtEmail.getText().toString(),binding.txtPassword.getText().toString());
                               //Getting the userId (generated by firebase),
                                String id = task.getResult().getUser().getUid();

                                //Adding the user to the realTime database , so we can have his id stored in real time
                                database.getReference().child("Users").child(id).setValue(user);


                                Toast.makeText( SignUpActivity.this, "Account Created Succesfully !", Toast.LENGTH_SHORT).show();

                            }
                            else
                            {
                                Toast.makeText(SignUpActivity.this, task.getException().toString(),Toast.LENGTH_SHORT).show();
                            }
                        }
                    });
                }
                else
                {
                    Toast.makeText( SignUpActivity.this, "Missing Credentials", Toast.LENGTH_SHORT).show();

                }
            }
        });

        // Move to Sign In page
        binding.txtAlreadyHaveAccount.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent = new Intent(SignUpActivity.this,SignInActivity.class);
                startActivity(intent);

            }
        });

    }
}